version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Optional, in case you use python scripts
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws sts get-caller-identity
      - echo Initializing Terraform...
      - terraform init

  build:
    commands:
      - echo Validating Terraform files...
      - terraform validate
      - echo Running Terraform plan...
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo Applying Terraform changes...
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
  discard-paths: no
